# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'Dear Friends' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'IQKeyboardManagerSwift'
  pod 'Alamofb878701113695917', '~> 5.2'
  pod 'SwiftyJSON'
  pod 'NVActivityIndicatorView' , '~> 4.8.0'
  pod 'Haptico', '1.1.1'
  pod 'SDWebImage', '~> 5.0'
  pod 'Hero'
  pod 'CropViewController'
  pod 'WXImageCompress', '~> 0.1.1'
  pod 'lottie-ios'
  pod 'BetterSegmentedControl'
  pod 'SKCountryPicker'
  pod 'BottomPopup'
  pod 'MSCircularSlider'
  pod 'CollectionViewPagingLayout'
  pod 'SkeletonView'
  pod 'NewPopMenu', '~> 2.0'
  pod 'SwiftyStoreKit'
  pod 'JXPageControl'
  pod 'Google-Mobile-Ads-SDK'
  pod 'GoogleAds-IMA-iOS-SDK', '~> 3.23.0'
  pod 'FLUtilities', :git => 'https://github.com/Nickelfox/FLUtilities.git', :branch => 'develop'
  pod 'FSCalendar'
  pod 'StepperView','~> 1.6.7'
  pod "NeatTipView"
  pod "ExpandableLabel"
  pod 'Stripe'
  pod 'Cache'
  pod 'MarqueeLabel'
  pod "youtube-ios-player-helper"
  pod 'YoutubePlayerView'
  pod 'GoogleSignIn'
  pod 'JWTDecode', '~> 3.1'
  pod 'SwiftAudioPlayer' , :git => 'https://github.com/Kuama-IT/SwiftAudioPlayer.git', :branch => 'fix-ios-16-crash'
  pod 'Mixpanel-swift'
  
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
        target.build_configurations.each do |config|
          config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
          config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
          config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
          xcconfig_path = config.base_configuration_reference.real_path
          xcconfig = File.read(xcconfig_path)
          xcconfig_mod = xcconfig.gsub(/DT_TOOLCHAIN_DIR/, "TOOLCHAIN_DIR")
          File.open(xcconfig_path, "w") { |file| file << xcconfig_mod }
          if config.build_settings['WRAPPER_EXTENSION'] == 'bundle'
            config.build_settings['DEVELOPMENT_TEAM'] = '342K49RF56'
          end
        end
      end
    end
  end
end
